apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/zk2
    server: 192.168.165.64
