apiVersion: v1
kind: Service
metadata:
  name: kube-system
  namespace: kube-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kube-system
  type: ClusterIP
