apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: im-test
#  lables:
#    name: traefik-ingress-lb
spec:
#  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: admin
    port: 8580
    targetPort: 8580
  selector:
    k8s-app: traefik-ingress-lb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: im-test
spec:
  rules:
  - host: ui.icsoc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-web-ui
          servicePort: web
